version: '3'

services:
  db:
    image: postgres
    hostname: ${POSTGRES_HOST}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/pyinvoice:/var/lib/postgresql/data
  web:
    image: pickleshb/pyinvoice
    build: .
    command: bin/docker_run.sh
    volumes:
      - .:/code
    ports:
      - "301:301"
    environment:
      - PRODUCTION=1
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db
