# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-21 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceNumber',
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_prefix',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='account_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='bank',
            field=models.CharField(default=None, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='sort_code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='address',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
    ]
