# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-21 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20170321_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 21, 19, 12, 31, 259370, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
