# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 24, 18, 55, 48, 955744, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
