# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-21 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='invoice_prefix',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
    ]
