# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-16 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='order',
        ),
    ]
