# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-16 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_invoice_utr'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='person',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
