# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20170908_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='utr',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
