# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20170416_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
    ]
