# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20170927_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='user_invoice_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
