# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20170927_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
    ]
