# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-30 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'invoice', '0012_expense'), (b'invoice', '0013_auto_20170928_0102')]

    dependencies = [
        ('invoice', '0011_invoice_is_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='invoice.Invoice')),
            ],
        ),
    ]
