# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_expensegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroup',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.ExpenseGroup'),
        ),
    ]
