# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20180103_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensegroup',
            options={'verbose_name': 'Expense Group', 'verbose_name_plural': 'Expense Groups'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_group', to='invoice.ExpenseGroup'),
        ),
    ]
