# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-15 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0019_auto_20180107_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
