# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-12 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_auto_20180415_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='person',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='phone',
        ),
    ]
