# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-12 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_invoice_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
