# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-24 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_invoice_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='require_utr',
            field=models.BooleanField(default=False),
        ),
    ]
